name: EnderPearl
main: com.eyeofender.enderpearl.EnderPearl
author: LimeByte
version: 0.3.0
database: true
commands:
    broadcast:
        description: Broadcasts a message to the specified server(s)
        usage: /<command> <server> <message...>
        permission: enderpearl.command.broadcast
    spawn:
        description: Teleports the player to the spawn
        usage: /<command>
        permission: enderpearl.command.spawn
    setspawn:
        description: Sets the spawn point
        usage: /<command>
        permission: enderpearl.command.setspawn
permissions:
    enderpearl.command.broadcast:
        description: Permission to use the broadcast command
        default: op
    enderpearl.command.spawn:
        description: Permission to use the spawn command
        default: true
    enderpearl.command.setspawn:
        description: Permission to use the setspawn command
        default: op