name: EnderPearl
main: com.eyeofender.enderpearl.EnderPearl
author: LimeByte
version: 1.4.0
database: true
commands:
    broadcast:
        description: Broadcasts a message to the specified server(s)
        usage: /<command> <server> <message...>
        permission: enderpearl.command.broadcast
        aliases: announce
    hub:
        description: Teleports the player to the hub
        usage: /<command>
        permission: enderpearl.command.hub
        aliases: leave
    setspawn:
        description: Sets the spawn point
        usage: /<command>
        permission: enderpearl.command.setspawn
        aliases: spawnset
    spawn:
        description: Teleports the player to the spawn
        usage: /<command>
        permission: enderpearl.command.spawn
    purchases:
        description: Lists your purchases
        usage: /<command>
        permission: enderpearl.command.purchases
    bans:
        description: Lists player bans
        usage: /<command>
        permission: enderpearl.command.bans
        aliases: banlist
    ban:
        description: Bans a player
        usage: /<command> <player> <time> <reason...>
        permission: enderpearl.command.ban
    pardon:
        description: Unbans a player
        usage: /<command> <player>
        permission: enderpearl.command.pardon
        aliases: unban
    baninfo:
        description: Lists player ban info
        usage: /<command> <player>
        permission: enderperal.command.baninfo
permissions:
    enderpearl.command.broadcast:
        description: Permission to use the broadcast command
        default: op
    enderpearl.command.hub:
        description: Permission to use the hub command
        default: true
    enderpearl.command.setspawn:
        description: Permission to use the setspawn command
        default: op
    enderpearl.command.spawn:
        description: Permission to use the spawn command
        default: true
    enderpearl.command.purchases:
        description: Permission to use the purchases command
        default: true
    enderpearl.command.bans:
        description: Permission to use the bans command
        default: op
    enderpearl.command.ban:
        description: Permission to use the ban command
        default: op
    enderpearl.command.pardon:
        description: Permission to use the pardon command
        default: op
    enderpearl.command.baninfo:
        description: Permission to use the baninfo command
        default: op
